apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n-staging
namePrefix: staging-

bases:
  - ../../base

resources:
  - namespace.yaml

patchesStrategicMerge:
  - patch-configmap.yaml